server:
  error:
    include-message: always
    include-binding-errors: always
  port: 10290

spring:
  datasource:
    url: jdbc:mysql://51.15.141.206:3308/coach?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: root
    password: N@tujengeroot

    #    url: jdbc:mysql://localhost:3306/coach?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
    #    username: root
    #    password: ninja

    #    url: jdbc:mysql://localhost:3306/coach?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
    #    username: root
    #    password: ninja

    #  url: jdbc:mysql://127.0.0.1:3306/coach?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
    # password: elijah@maria22
    #username: elijah


    #  url: jdbc:mysql://127.0.0.1:3306/coach?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
    # password: elijah@maria22
    #username: elijah




  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

#logging:
#  level:
#    org.hibernate.SQL: info
#    org.hibernate.type: trace
#    com.natujenge.thecouch: info