server:
  error:
    include-message: always
    include-binding-errors: always
  port: 10290

spring:
  datasource:
    url: jdbc:mysql://51.15.141.206:3308/coach?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: root
    password: N@tujengeroot

#        url: jdbc:mysql://172.18.0.2:3306/thecoach?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
#        username: root
#        password: root


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#  servlet:
#    multipart:
#
#      max-file-size: 10MB    # Set the maximum file size if needed
#      max-request-size: 10MB  # Set the maximum request size if needed

#logging:
#  level:
#    org.hibernate.SQL: info
#    org.hibernate.type: trace
#    com.natujenge.thecouch: info