server:
  error:
    include-message: always
    include-binding-errors: always
  port: 9090

spring:
  datasource:
    password: david123
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/thecoach
    username: david
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher